blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/tvinke/algorilla/discussions
    about: Ask questions, share ideas, or show what you've built with algorilla
