complexity:
  LongMethod:
    threshold: 30
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15
  CyclomaticComplexMethod:
    threshold: 15
  LargeClass:
    threshold: 200

style:
  MaxLineLength:
    maxLineLength: 140
    excludeCommentStatements: true
  WildcardImport:
    active: false
  ReturnCount:
    max: 5

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
    propertyPattern: '[a-z][a-zA-Z0-9]*'
